server:
  port: 8082
spring:
  application.name: ecommerce-inventory-service
  output.ansi.enabled: ALWAYS
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

# === OAuth2 ====
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180

      client:
        registration:
          ecommerce-inventory-service:
            provider: spring
            client-id: ecommerce-inventory-service
            client-secret: inventory-client-secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: client_credentials
            scope: admin
        provider:
          spring:
            issuer-uri: http://localhost:8180
            authorization-uri: http://localhost:8180/oauth2/authorize

  # === Database ===
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_inventory_service_db
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true

  # === Kafka ===
  kafka:
    bootstrap-servers: http://localhost:9094

# === Actuator ===
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  health:
    circuitbreakers.enabled: true
    ratelimiters.enabled: true

# === Circuit breaker configuration for 'uploadServiceCircuitBreaker' ===
resilience4j:
  circuitbreaker:
    instances:
      uploadServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: false
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 100
  ratelimiter:
    instances:
      uploadServiceCircuitBreaker:
        limitRefreshPeriod: 60s
        limitForPeriod: 2
        timeoutDuration: 0s
        registerHealthIndicator: true

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  override-with-generic-response: false
  api-docs:
    version: openapi_3_0
    enabled: true
    path: /inventory-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /inventory-service/swagger-ui.html

uploadService.url: http://localhost:8085/api/internal/uploads
