server:
  port: 8083
spring:
  application.name: ecommerce-discount-service
  output.ansi.enabled: ALWAYS

  # === OAuth2 ====
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180

      client:
        registration:
          ecommerce-discount-service:
            provider: spring
            client-id: ecommerce-discount-service
            client-secret: discount-client-secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: client_credentials
            scope: admin
        provider:
          spring:
            issuer-uri: http://localhost:8180
            authorization-uri: http://localhost:8180/oauth2/authorize

  # === Database ===
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_discount_service_db
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  override-with-generic-response: false
  api-docs:
    version: openapi_3_0
    enabled: true
    path: /discount-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /discount-service/swagger-ui.html

services:
  inventory-service.url: http://localhost:8082/api/v1/promotions
