services:
  prometheus:
    container_name: "prometheus"
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - observability_net
  grafana:
    container_name: "grafana"
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - observability_net

volumes:
  prometheus_data:
    name: "prometheus_data"
  grafana_data:
    name: "grafana_data"

networks:
  observability_net:
    driver: bridge
    name: "observability_net"
