global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "ecommerce-customer-service-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8081"]
        labels:
          application: "ecommerce-customer-service"