server:
  port: 8081
spring:
  application.name: ecommerce-customer-service
  output.ansi.enabled: ALWAYS

# === OAuth2 ===
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180

      client:
        registration:
          ecommerce-customer-service:
            provider: spring
            client-id: ecommerce-customer-service
            client-secret: customer-client-secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: client_credentials
            scope: read,write,admin
        provider:
          spring:
            issuer-uri: http://localhost:8180
            authorization-uri: http://localhost:8180/oauth2/authorize

# === Database ===
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_customer_service_db
    username: postgres
    password: postgres
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true

# === Actuator ===
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  health:
    circuitbreakers.enabled: true
    ratelimiters.enabled: true

# === Circuit breaker configuration for 'createCustomerCircuitBreaker' ===
resilience4j:
  circuitbreaker:
    instances:
      createCustomerCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: false
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 100
#  retry:
#    instances:
#      createCustomerCircuitBreaker:
#        maxAttempts: 3
#        waitDuration: 2000ms
  ratelimiter:
    instances:
      createCustomerCircuitBreaker:
        limitRefreshPeriod: 60s
        limitForPeriod: 2
        timeoutDuration: 0s
        registerHealthIndicator: true

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# === External services ===
external:
  services:
    auth-server:
      internal-uri: http://localhost:8180/auth/internal/users
    cart-service:
      uri: http://localhost:8084/api/v1/carts

springdoc:
  override-with-generic-response: false
  api-docs:
    version: openapi_3_0
    enabled: true
    path: /customer-service/v3/api-docs
  swagger-ui:
    enabled: true
    path: /customer-service/swagger-ui.html